"use client";
import Head from "next/head";

import type { Metadata } from "next";
import "./globals.css";
import { store } from "./components/ReduxToolKit/store";
import { Provider } from "react-redux";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// import { headers } from 'next/headers'
// import { cookieToInitialState } from "wagmi";
// import { config } from "@/config";
// import Web3ModalProvider from "@/app/components/Wallets/WalletConnect/Web3ModalProvider";

// export const metadata: Metadata = {
//   title: "Air-Hive",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </Head>
      <body>
        <ToastContainer />
        {/* <Web3ModalProvider initialState={initialState}> */}
        <Provider store={store}>{children}</Provider>
        {/* </Web3ModalProvider> */}
      </body>
    </html>
  );
}
